name: themansion
description: An app for my mansion, The Mansion!
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: any
  path_provider: any
  flutter_localizations:
    sdk: flutter
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Ostrich
      fonts:
        - asset: assets/fonts/Ostrich.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster.ttf
